name: Docker Image CI

on:
  push:
    branches: [ "main", "4-github-actions" ]
  pull_request:
    branches: [ "main", "4-github-actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)